[package]
name = "transmission"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"

[dependencies]
uuid = { version = "1", features = ["v4", "fast-rng", "macro-diagnostics", "js"] }
